---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the previously present group is absent"
    ansible.builtin.shell: "! getent group present-to-absent"
    changed_when: false
