---
# the sysctl configuration
linux_sysctl: []
# - name: string
#   value: string | d(omit)
#   reload: boolean | d('yes')
#   sysctl_file: string | d(omit)
#   state: enum('absent', 'present') | d('present')
