---
# the sysctl package state ('present', 'latest')
linux_sysctl_state: 'present'

# the sysctl variable list
## - name: string
##   value: string | d(omit)
##   reload: boolean | d(true)
##   sysctl_file: string | d(omit)
##   state: enum('present', 'absent') | d('present')
linux_sysctl: []
...
