---
- name: "prepare"
  hosts: "all"

  tasks:
  - import_role:
      name: "cron"
    vars:
      linux_cron:
      - { name: "test_job_001", job: "/usr/bin/true" }
      - { name: "test_job_002", job: "/usr/bin/true", user: "nobody", day: "1", hour: "22", minute: "30", month: "6", weekday: "3" }
