---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the test_job_001 is present"
    ansible.builtin.cron:
      name: "test_job_001"
      job: "/usr/bin/false"
      state: "present"
  - name: "assert that the test_job_002 is present"
    ansible.builtin.cron:
      name: "test_job_002"
      job: "/usr/bin/false"
      user: "root"
      day: "2"
      hour: "23"
      minute: "45"
      month: "3"
      weekday: "5"
      state: "present"
