---
- name: 'prepare'
  hosts: 'all'

  tasks:
  - ansible.builtin.apt:
      name: 'procps'
      update_cache: true

  - ansible.posix.sysctl:
      name: 'vm.swappiness'
      value: '60'
      reload: false

  - ansible.posix.sysctl:
      name: 'vm.panic_on_oom'
      value: '1'
      reload: false
