---
- name: 'prepare'
  hosts: 'all'

  tasks:
  - ansible.builtin.import_role:
      name: 'user'
    vars:
      linux_user:
      - { name: 't_user_001', uid: 915 }
      - { name: 't_user_002', comment: 't_user_002', home: '/opt/t_user_002', shell: '/bin/bash', uid: 916 }
