---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the previously present group is present"
    ansible.builtin.shell: "getent group present-to-present"
    changed_when: false
