---
- name: "(linux.hostname) set system hostname"
  ansible.builtin.hostname:
    name: "{{ linux_hostname | mandatory }}"
  when: "linux_hostname is defined"
  tags: ["role::hostname", "task::configure"]
