---
- name: 'Assert that the HostName State Value is Valid'
  ansible.builtin.assert:
    that:
    - linux_hostname__state in [ 'present', 'latest' ]
    msg: 'The `linux_hostname__state` must be one of [ "present", "latest" ] - "{{ linux_hostname__state }}" is not supported'
    quiet: true
  tags: [ 'always' ]

#
# Install
#

- name: 'Install | Install or Update the HostName Support via APT'
  ansible.builtin.apt:
    name: '{{ linux_hostname__package_name }}'
    update_cache: true
    cache_valid_time: 1800
    state: '{{ linux_hostname__state }}'
  tags: [ 'role:hostname', 'role:hostname:install', 'task:install' ]

#
# Configure
#

- name: 'Configure | Set the HostName'
  # @see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html
  ansible.builtin.hostname:
    name: '{{ linux_hostname | mandatory }}'
    use: 'systemd'
  when:
  - linux_hostname is defined
  tags: [ 'role:hostname', 'role:hostname:configure', 'task:configure' ]
...
