workflow:
  rules:
  - if: $CI_COMMIT_BRANCH

stages:
- test

molecule test:
  image: python:3.10
  stage: test
  before_script:
  - apt update
  - apt install -y podman
  - podman info
  - python3 --version
  - python3 -m pip install ansible ansible-lint molecule molecule[podman] yamllint
  - ansible --version
  - molecule --version
  script:
  - make test
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
