---
namespace: havlasme
name: linux
version: 0.1.1
readme: README.md
authors:
- Tomáš Havlas <tomas@havlas.me>
description: An Ansible collection of linux management content.
license_file: LICENSE
dependencies:
  'havlasme.ansible': '*'
tags:
- linux
repository: https://gitlab.com/havlas.me/ansible-collection-linux
documentation: https://gitlab.com/havlas.me/ansible-collection-linux
homepage: https://gitlab.com/havlas.me/ansible-collection-linux
issues: https://gitlab.com/havlas.me/ansible-collection-linux/-/issues
build_ignore:
- .ansible-lint
- .cache
- .gitignore
- .gitlab-ci.yml
- .idea
- .yamllint
- dist
- Makefile
- roles/*/.ansible-lint
- roles/*/.yamllint
