---
- name: "(linux.user) create, update, and remove authorized keys"
  ansible.posix.authorized_key:
    key: "{{ item.1.key | mandatory }}"
    key_options: "{{ item.1.key_options | default(omit) }}"
    comment: "{{ item.1.comment | default(omit) }}"
    exclusive: "{{ item.1.exclusive | default(omit) }}"
    user: "{{ item.0.name | mandatory }}"
    state: "{{ item.1.state | default('present') }}"
  loop: "{{ linux_user | subelements('authorized_key', skip_missing='yes') }}"
  when: item.0.state | default('present') == 'present'
