---
- name: "(linux.user) create, update, and remove system user"
  ansible.builtin.user:
    name: "{{ item.name | mandatory }}"
    comment: "{{ item.comment | d(omit) }}"
    group: "{{ item.group | d(omit) }}"
    home: "{{ item.home | d(omit) }}"
    password: "{{ item.password | d(omit) }}"
    shell: "{{ item.shell | d(omit) }}"
    system: "{{ item.system | d(omit) }}"
    uid: "{{ item.uid | d(omit) }}"
    state: "{{ item.state | d('present') }}"
  loop: "{{ linux_user }}"
  tags: ["user", "configure"]

- import_tasks: "authorized-key.yml"
  tags: ["user", "configure"]
