---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that `t_group_001` group is present'
    ansible.builtin.group:
      name: 't_group_001'
      gid: 1015
      state: 'present'
