---
- name: 'Chrony | Restart Service'
  ansible.builtin.systemd:
    name: '{{ chrony__service_name }}'
    daemon_reload: true
    state: 'restarted'
  when:
  - chrony__ansible_restart | bool
  - chrony__state != 'absent'
  - not ansible_check_mode
  tags: [ 'always' ]
...
