---
- name: 'converge'
  hosts: 'all'

  tasks:
  - ansible.builtin.import_role:
      name: 'mount'
    vars:
      linux_mount:
      - { name: '/mnt/t_mount_001', src: 'tmpfs', fstype: 'tmpfs' }
      - { name: '/mnt/t_mount_002', src: 'tmpfs', fstype: 'tmpfs', state: 'mounted' }
      - { name: '/mnt/t_mount_003', boot: true, src: 'tmpfs', fstype: 'tmpfs', opts: 'ro' }
