---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that `t_mount_001` mount point is mounted'
    ansible.posix.mount:
      name: '/mnt/t_mount_001'
      src: 'tmpfs'
      fstype: 'tmpfs'
      state: 'mounted'
  - name: 'assert that `t_mount_002` mount point is mounted'
    ansible.posix.mount:
      name: '/mnt/t_mount_002'
      src: 'tmpfs'
      fstype: 'tmpfs'
      state: 'mounted'
  - name: 'assert that `t_mount_003` mount point is mounted'
    ansible.posix.mount:
      name: '/mnt/t_mount_003'
      src: 'tmpfs'
      boot: true
      fstype: 'tmpfs'
      opts: 'ro'
      state: 'mounted'
