---
- name: "(linux.motd) deploy the main motd"
  ansible.builtin.template:
    dest: "{{ linux_motd | mandatory }}"
    src: "{{ linux_motd_tmpl | mandatory }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "linux_motd_tmpl is defined"
