---
- name: 'linux | motd | set motd message'
  ansible.builtin.template:
    dest: '{{ linux_motd_file }}'
    src: '{{ linux_motd_template }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
  - linux_motd_template is defined
