---
- name: 'Configure | Delete a Message of the Day (MOTD) Conf File'
  ansible.builtin.file:
    name: '{{ item.dest | mandatory }}'
    state: 'absent'
  loop: '{{ linux_motd | selectattr("state", "havlasme.ansible.is_absent") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  tags: [ 'role:motd', 'role:motd:configure', 'task:configure' ]

- name: 'Configure | Create and Update a Message of the Day (MOTD) Conf File'
  ansible.builtin.template:
    dest: '{{ item.dest | mandatory }}'
    src: '{{ item.tmpl | mandatory }}'
    owner: '{{ item.user | d("root") }}'
    group: '{{ item.group | d("root") }}'
    mode: '{{ item.mode | d("0755") }}'
    backup: '{{ item.backup | d(false) }}'
  loop: '{{ linux_motd | selectattr("state", "havlasme.ansible.is_present") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  tags: [ 'role:motd', 'role:motd:configure', 'task:configure' ]
...
