---
- name: 'converge'
  hosts: 'all'

  tasks:
  - ansible.builtin.include_role:
      name: 'motd'
    vars:
      linux_motd__template: 'etc/motd.j2'
      linux_motd__update_motd:
      - { dest: '/etc/update-motd.d/10-uname', tmpl: 'etc/update-motd.d/10-uname.j2' }
      - { dest: '/etc/update-motd.d/20-uname', state: 'absent' }
