---
- name: 'converge'
  hosts: 'all'

  tasks:
  - ansible.builtin.include_role:
      name: 'motd'
    vars:
      linux_motd:
      - { dest: '/etc/motd', tmpl: 'etc/motd.j2', mode: '0644' }
      - { dest: '/etc/update-motd.d/10-uname', tmpl: 'etc/update-motd.d/10-uname.j2' }
      - { dest: '/etc/update-motd.d/20-uname', state: 'absent' }
