---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the t_mount_001 is mounted"
    ansible.posix.mount:
      name: "/mnt/t_mount_001"
      src: "tmpfs"
      fstype: "tmpfs"
      opts: "ro"
      state: "mounted"
