---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that `t_cronjob_001` job is present'
    ansible.builtin.cron:
      name: 't_cronjob_001'
      job: '/usr/bin/false'
      state: 'present'
  - name: 'assert that `t_cronjob_002` job is present'
    ansible.builtin.cron:
      name: 't_cronjob_002'
      job: '/usr/bin/false'
      user: 'root'
      day: '2'
      hour: '23'
      minute: '45'
      month: '3'
      weekday: '5'
      state: 'present'
