---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the test_group_001 is absent"
    ansible.builtin.group:
      name: "test_group_001"
      state: "absent"
    changed_when: false
