---
- name: 'converge'
  hosts: 'all'

  tasks:
  - ansible.builtin.import_role:
      name: 'user'
    vars:
      linux_user:
      - { name: 't_user_001' }
      - { name: 't_user_002', state: 'present' }
      - { name: 't_user_003', comment: 't_user_003', home: '/opt/t_user_003', shell: '/bin/sh', uid: 1015 }
