---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that the t_user_001 is present'
    ansible.builtin.user:
      name: 't_user_001'
      state: 'present'
  - name: 'assert that the t_user_002 is present'
    ansible.builtin.user:
      name: 't_user_002'
      state: 'present'
  - name: 'assert that the t_user_003 is present'
    ansible.builtin.user:
      name: 't_user_003'
      comment: 't_user_003'
      home: '/opt/t_user_003'
      shell: '/bin/sh'
      uid: 1015
      state: 'present'
