---
- name: "converge"
  hosts: "all"

  tasks:
  - import_role:
      name: "mount"
    vars:
      linux_mount:
      - { name: "/opt/test_mount_001", src: "tmpfs", fstype: "tmpfs" }
      - { name: "/opt/test_mount_002", src: "tmpfs", fstype: "tmpfs", state: "mounted" }
      - { name: "/opt/test_mount_003", boot: "yes", src: "tmpfs", fstype: "tmpfs", opts: "ro" }
