---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the test_mount_001 is mounted"
    ansible.posix.mount:
      name: "/opt/test_mount_001"
      src: "tmpfs"
      fstype: "tmpfs"
      state: "mounted"
  - name: "assert that the test_mount_002 is mounted"
    ansible.posix.mount:
      name: "/opt/test_mount_002"
      src: "tmpfs"
      fstype: "tmpfs"
      state: "mounted"
  - name: "assert that the test_mount_003 is mounted"
    ansible.posix.mount:
      name: "/opt/test_mount_003"
      src: "tmpfs"
      boot: "yes"
      fstype: "tmpfs"
      opts: "ro"
      state: "mounted"
