---
- name: "converge"
  hosts: "all"

  tasks:
  - import_role:
      name: "user"
    vars:
      linux_user:
      - { name: "test_user_001", uid: 1015 }
      - { name: "test_user_002", comment: "test_case_002", home: "/opt/test_case_002", shell: "/bin/sh", uid: 1016 }
