---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the test_user_001 is present"
    ansible.builtin.user:
      name: "test_user_001"
      system: "yes"
      state: "present"
    changed_when: false
