---
- name: "converge"
  hosts: "all"

  tasks:
  - import_role:
      name: "sysctl"
    vars:
      linux_sysctl:
      - name: "vm.swappiness"
        value: "10"
        state: "present"
        reload: "no"
