---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the t_group_001 is present"
    ansible.builtin.group:
      name: "t_group_001"
      state: "present"
  - name: "assert that the t_group_002 is present"
    ansible.builtin.group:
      name: "t_group_002"
      state: "present"
  - name: "assert that the t_group_003 is present"
    ansible.builtin.group:
      name: "t_group_003"
      gid: 915
      system: "yes"
      state: "present"
