---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
- name: linux-sysctl-debian
  image: docker.io/pycontribs/debian:latest
  pre_build_image: true
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
