---
- name: "converge"
  hosts: "all"

  tasks:
  - import_role:
      name: "user"
    vars:
      linux_user:
      - { name: "test_user_001" }
      - { name: "test_user_002", state: "present" }
      - { name: "test_user_003", system: "yes" }
