---
- name: "(linux.sysctl) add, update, and remove sysctl configuration"
  ansible.posix.sysctl:
    name: "{{ item.name | mandatory }}"
    value: "{{ item.value | d(omit) }}"
    reload: "{{ item.reload | d('yes') }}"
    sysctl_file: "{{ item.sysctl_file | d(omit) }}"
    state: "{{ item.state | d('present') }}"
  loop: "{{ linux_sysctl }}"
