---
- name: "(linux.sysctl) include os specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "(linux.sysctl) install required package"
  ansible.builtin.package:
    name: "{{ sysctl_package }}"
    state: "present"
  when: "linux_sysctl | length > 0"
