---
- name: "prepare"
  hosts: "all"

  tasks:
  - import_role:
      name: "sysctl"
    vars:
      linux_sysctl:
      - { name: "kernel.panic", value: "3", reload: "no" }
      - { name: "net.ipv4.ip_forward", value: "1", reload: "no" }
