---
- name: 'converge'
  hosts: 'all'

  tasks:
  - ansible.builtin.include_role:
      name: 'user'
    vars:
      linux_user:
      - name: 'authorized_key'
        authorized_key:
        - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA+D3ADacdaWs4kt0ByWkSDVUyuUYofPQdrQgVh0Pb10
          comment: 'create_authorized_key'
        - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIK7MsqcwtJbwCprJMYpe/rycy6Y2vF8f0qowFSrO0bl
          comment: 'update_authorized_key'
          key_options: 'no-port-forwarding'
        - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH9/ZyBo/4EwjB6pp2Qp14cUsWbPt7TSXG06pq3OaRTr
          state: 'absent'
