---
- name: 'prepare'
  hosts: 'all'

  tasks:
  - ansible.builtin.user:
      name: 'authorized_key'

  - ansible.posix.authorized_key:
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIK7MsqcwtJbwCprJMYpe/rycy6Y2vF8f0qowFSrO0bl
      comment: 'update_authorized_key'
      key_options: 'no-port-forwarding'
      user: 'authorized_key'

  - ansible.posix.authorized_key:
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH9/ZyBo/4EwjB6pp2Qp14cUsWbPt7TSXG06pq3OaRTr
      comment: 'delete_authorized_key'
      user: 'authorized_key'
