---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that the `create_authorized_key` key is present'
    ansible.posix.authorized_key:
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA+D3ADacdaWs4kt0ByWkSDVUyuUYofPQdrQgVh0Pb10
      comment: 'create_authorized_key'
      user: 'authorized_key'
    register: result
    failed_when: result.changed

  - name: 'assert that the `update_authorized_key` key is present'
    ansible.posix.authorized_key:
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIK7MsqcwtJbwCprJMYpe/rycy6Y2vF8f0qowFSrO0bl
      comment: 'update_authorized_key'
      key_options: 'no-port-forwarding'
      user: 'authorized_key'
    register: result
    failed_when: result.changed

  - name: 'assert that the `delete_authorized_key` key is absent'
    ansible.posix.authorized_key:
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH9/ZyBo/4EwjB6pp2Qp14cUsWbPt7TSXG06pq3OaRTr
      comment: 'delete_authorized_key'
      user: 'authorized_key'
      state: 'absent'
    register: result
    failed_when: result.changed
