---
- name: "prepare"
  hosts: "all"

  tasks:
  - name: "install required package"
    ansible.builtin.package:
      name: "procps"
      state: "present"
  - name: "prepare sysctl config state present -> absent"
    ansible.posix.sysctl:
      name: "vm.swappiness"
      value: "10"
      state: "present"
      reload: "no"
