---
- name: "converge"
  hosts: "all"

  tasks:
  - import_role:
      name: "cron"
    vars:
      linux_cron:
      - { name: "test_job_001", job: "/usr/bin/true" }
      - { name: "test_job_002", job: "/usr/bin/true" }
      - { name: "test_job_003", job: "/usr/bin/true", state: "absent" }
