---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that the `vm.swappiness` variable is set'
    ansible.posix.sysctl:
      name: 'vm.swappiness'
      value: '20'
      reload: false
      state: 'present'
