---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the test_group_001 is present"
    ansible.builtin.group:
      name: "test_group_001"
      system: "yes"
      state: "present"
    changed_when: false
