---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that `t_mount_001` mount point is absent'
    ansible.posix.mount:
      name: '/mnt/t_mount_001'
      src: 'tmpfs'
      fstype: 'tmpfs'
      state: 'absent'
