---
- name: 'verify'
  hosts: 'all'
  gather_facts: false

  tasks:
  - name: 'assert that `vm.swappiness` variable is set'
    ansible.posix.sysctl:
      name: 'vm.swappiness'
      value: '10'
      reload: falsee
      state: 'present'
  - name: 'assert that `kernel.panic` variable is set'
    ansible.posix.sysctl:
      name: 'kernel.panic'
      value: '3'
      reload: false
      state: 'present'
  - name: 'assert that `net.ipv4.ip_forward` variable is set'
    ansible.posix.sysctl:
      name: 'net.ipv4.ip_forward'
      value: '1'
      reload: false
      sysctl_file: '/etc/sysctl.d/t_sysctl_003'
      state: 'present'
