---
- name: 'prepare'
  hosts: 'all'

  tasks:
  - ansible.posix.mount:
      name: '/mnt/update_mount'
      src: 'tmpfs'
      fstype: 'tmpfs'
      opts: 'ro'
      state: 'mounted'

  - ansible.posix.mount:
      name: '/mnt/delete_mount'
      src: 'tmpfs'
      fstype: 'tmpfs'
      opts: 'rw'
      state: 'mounted'
