---
- name: 'linux |timezone | set timezone'
  community.general.timezone:
    name: '{{ linux_timezone }}'
    hwclock: '{{ linux_timezone_hwclock | d(omit) }}'
  when:
  - linux_timezone is defined
