---
- name: "converge"
  hosts: "all"

  tasks:
  - import_role:
      name: "group"
    vars:
      linux_group:
      - { name: "test_group_001" }
      - { name: "test_group_002", system: "Yes" }
      - { name: "test_group_003", state: "absent" }
