---
- name: 'linux | group | create, update, or delete local group'
  ansible.builtin.group:
    name: '{{ item.name | mandatory }}'
    gid: '{{ item.gid | d(omit) }}'
    system: '{{ item.system | d(omit) }}'
    state: '{{ item.state | d("present") }}'
  loop: '{{ linux_group }}'
  loop_control:
    label: '{{ item.name }} | {{ item.state | d("present") }}'
...
