---
dependencies: []

galaxy_info:
  description: An Ansible role to manage local groups on Debian.
  author: havlas.me
  company: havlas.me
  issue_tracker_url: https://gitlab.com/havlas.me/ansible-collection-linux/-/issues
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - group
  - linux
