---
dependencies:
- '_compat_check'

galaxy_info:
  description: An Ansible role to manage linux system users and associated authorized keys on Debian and Ubuntu running systemd.
  author: havlas.me
  company: havlas.me
  issue_tracker_url: https://gitlab.com/havlas.me/ansible-collection-linux/-/issues
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
    - bullseye
    - bookworm
  - name: Ubuntu
    versions:
    - focal
    - jammy
    - noble
  galaxy_tags:
  - linux
  - user
