---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the test_job_001 is present"
    ansible.builtin.cron:
      name: "test_job_001"
      job: "/usr/bin/true"
      user: "root"
      state: "present"
    changed_when: false
  - name: "assert that the test_job_002 is present"
    ansible.builtin.cron:
      name: "test_job_002"
      job: "/usr/bin/true"
      user: "root"
      state: "present"
    changed_when: false
  - name: "assert that the test_job_003 is present"
    ansible.builtin.cron:
      name: "test_job_003"
      job: "/usr/bin/true"
      user: "nobody"
      day: "1"
      hour: "22"
      minute: "30"
      month: "6"
      weekday: "3"
      state: "present"
    changed_when: false
  - name: "assert that the test_job_004 is present"
    ansible.builtin.cron:
      name: "test_job_004"
      job: "/usr/bin/true"
      user: "root"
      cron_file: "/etc/cron.d/test_job_004"
      state: "present"
    changed_when: false
