---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that test_case_00101 is present"
    ansible.posix.authorized_key:
      key: >-
        ecdsa-sha2-nistp256
        AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDwP3Ydc0NGLJ76V/lXVvIHnQ/2+fJWeVMYvlFpZiNt4G3Oy4v7pmVaaG3NwJu3HEiwSBsmCxbx6wUVYtGyxwls=
        test_case_00101
      user: "test_case_001"
      state: "present"
  - name: "assert that test_case_00102 is present"
    ansible.posix.authorized_key:
      key: >-
        ecdsa-sha2-nistp256
        AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOPhW/l7k3cwk4jqXw+cKoGhAHzqezpT/wryGy45Ei4VgfKi6LJm+djtIlTcS3RET00lWo6Rm/DCAjN+NHXk7e0=
        test_case_00102
      user: "test_case_001"
      state: "present"
  - name: "assert that test_case_00103 is present"
    ansible.posix.authorized_key:
      key: >-
        ecdsa-sha2-nistp256
        AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCJEhDtXPEsmJ6HeS23o9qQMgvnzY8+DLG2kmWDHfdnObsYGbhe+imNfcbaJ+wZxLFkfTCorl1ce+/o9zFGyuVM=
        test_case_00103
      comment: "test_case_00103"
      key_options: "no-port-forwarding"
      user: "test_case_001"
      state: "present"
