---
- name: "prepare"
  hosts: "all"

  tasks:
  - import_role:
      name: "cron"
    vars:
      linux_cron_job:
      - { name: "t_cronjob_001", job: "/usr/bin/true" }
      - { name: "t_cronjob_002", job: "/usr/bin/true", cron_file: "/etc/cron.d/t_cronjob_002" }
