---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the t_cronjob_001 is absent"
    ansible.builtin.cron:
      name: "t_cronjob_001"
      state: "absent"
  - name: "assert that the t_cronjob_002 is absent"
    ansible.builtin.cron:
      name: "t_cronjob_002"
      cron_file: "/etc/cron.d/t_cronjob_002"
      state: "absent"
