---
# the user list
linux_user: []
# - name: string
#   comment: string | d(omit)
#   group: string | d(omit)
#   home: string | d(omit)
#   password: string | d(omit)
#   shell: string | d(omit)
#   system: boolean | d(omit)
#   uid: integer | d(omit)
#   state: enum('absent', 'present') | d('present')
#   authorized_key: [ ]
#   - key: string
#     key_options: string | d(omit)
#     comment: string | d(omit)
#     exclusive: boolean | d(omit)
#     state: enum('absent', 'present') | d('present')
