---
- name: "verify"
  hosts: "all"
  gather_facts: false

  tasks:
  - name: "assert that the config is present in alternative file"
    ansible.builtin.lineinfile:
      path: "/etc/sysctl.d/40-alternative-present.conf"
      line: "vm.swappiness=10"
      state: "present"
